### ISSUE TITLE
[Bug report/Feature request] Can't jump gaps

### ISSUE THREAD

**Issue by JustCallMeQuincy** [ControlCompany/ControlCompany#10]
# Describe the bug
The jumps in the game are not possible right now, since the "NPCs" can't physically jump.
Maybe - like the game handles it - a teleport would fix the issue in a "realistic" manner (when you're trying to blend in with the AI, for example)

# What is supposed to happen?
You should be able to do the jumps and not get stuck at the bottom.

# What actually happens?
You can't jump and thus fall.

# Illustration of the issue
https://youtu.be/fFwF94s9m3Q

**Comment by AverageVirusTotalEnjoyer** [comment]
It would be a feature more than a bug

**Comment by JustCallMeQuincy** [comment]
I suppose it could count as both, though it does inhibit the gameplay since those jumps are simply not possible, even in Ghost mode (since Ghost mode also can't jump)

**Comment by JustCallMeQuincy** [comment]
Calling it an oversight would be the most accurate way of describing it

**Comment by Cornish-Kap** [comment]
would it be possible to make it so you just walk on air while over gaps maybe?

**Comment by klampzlamps** [comment]
This is indeed on my radar of things to fix, the quick fix would be to let you jump but the downside would be that jumping monsters don't make sense. The other potential fix would be to build an invisible bridge over the gaps that you could walk on.

In any case I will definitely look into it! Thanks!

**Comment by JustCallMeQuincy** [comment]
> would it be possible to make it so you just walk on air while over gaps maybe?

Great idea ngl :D
Way simpler too, I like your thinking

**Comment by klampzlamps** [comment]
Jumping was added a few patches ago, closing.
