### ISSUE TITLE
Voices only comming out  of afk Body

### ISSUE THREAD

**Issue by Dem0nVA** [ControlCompany/ControlCompany#100]
**Describe the bug**
I can only be heard as a monster when near my alive body and when dead I cant be heard at all

**Comment by JustCallMeQuincy** [comment]
What exactly do you mean by "voices"?
Do you mean your own voice?

**Comment by Dem0nVA** [comment]
What I mean is when I'm a monster My voice is only heard from my crewmate body

**Comment by klampzlamps** [comment]
That’s the intended behaviour, closing as non-issue. For a feature request of the mic from the monster refer to #25
