### ISSUE TITLE
Mod missing

### ISSUE THREAD

**Issue by DTGRIK** [ControlCompany/ControlCompany#101]
mod not showing i check from lethal config
install by thunder app
v. 1.0.7
![Screenshot 2024-01-17 220936](https://github.com/ControlCompany/ControlCompany/assets/78967256/e00bd731-0feb-4258-93e6-e10eabc8411a)

**Comment by klampzlamps** [comment]
What window/browser is this? Have you tried hosting a game and pulling the lever?

**Comment by DTGRIK** [comment]
it from https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/ i hosting but not pull the lever wait for my friend join the game

**Comment by DTGRIK** [comment]
ok my bad its work it just my panic because i cant see how to keybind this mod
