### ISSUE TITLE
Mod refuses to wrok

### ISSUE THREAD

**Issue by pvzsupersanicman** [ControlCompany/ControlCompany#102]
**Describe the bug**
When I press F1 nothing happens, I don't go into ghost mode and I can't change into monsters 

**Expected behavior**
I normally expect for ghost mode when I press F1 but for some reason even though the mod is installed it wont work!

**Screenshots**
![image](https://github.com/ControlCompany/ControlCompany/assets/156940627/2ccf292d-0a39-41fe-9604-23ad92c6c215)

As you can see there is nothing talking about ghost mode

**Mod version (please complete the following information):**
I currently have the most recent version

**Additional context**
Frankly I dont think the mod is even running

**Comment by TheCompany12** [comment]
im having the same problem, been trying to make this work since yesterday.

**Comment by JustCallMeQuincy** [comment]
You have to pull the level and spawn into a level for the controls to show up

**Comment by pvzsupersanicman** [comment]
I fixed it
