### ISSUE TITLE
The ability to delete a spawned monster

### ISSUE THREAD

**Issue by stevebalk** [ControlCompany/ControlCompany#105]
**Problem:**
- Balance
     I don't want to make the game unbalance the game for my friends, when i let go of a spawned monster.

**Solution:**
- Monster delete function
      It would be awesome when i just could say "Ok, i'm done scaring my friends. Now i go back into the shadows and delete the monster and don't let it roam freely"

**Context:**
I made a modpack for my friends and they don't know that i can spawn/control monsters. So it is really funny.
But i don't want to spawn dangerous monsters that destroy the balance when i leave them.

**Comment by klampzlamps** [comment]
This is how the mod works currently, the monsters are deleted once you exit. If not then most likely another mod is interfering.
