### ISSUE TITLE
The mod doesn't work for me

### ISSUE THREAD

**Issue by JudarSusje1334** [ControlCompany/ControlCompany#107]
I installed the mod from Thunderstore with version 1.0.7 supposedly.

When I started the game with the mod already installed, it did not run or similar, causing it to not work, which is why it seemed like I did not have the mod installed. I tried several times downloading other versions but it didn't let me, currently I can't post screenshots due to lack of time. Thank you

**Comment by JustCallMeQuincy** [comment]
Did you: 
1. Click on `Start modded`
2. Host a game
3. Pull the ship lever to land on a moon
