### ISSUE TITLE
It does not work with the newest BepInEx version (i think)

### ISSUE THREAD

**Issue by Cristatron** [ControlCompany/ControlCompany#108]
Just when I launch the game the mods does not work and in the little console it says something about the version of BepInEx I'm using and I can't use and older version so I can't play the mod

**Comment by JustCallMeQuincy** [comment]
Did you:
1. Click on `Start modded`
2. Host a game
3. Pull the ship lever to spawn into the world

**Comment by JustCallMeQuincy** [comment]
Closing this issue, assuming it's been resolved.
