### ISSUE TITLE
Problem with voice chat after activating the mod. 

### ISSUE THREAD

**Issue by artemGAVxyliGUN** [ControlCompany/ControlCompany#109]
**Describe the bug**
When we landed on planet Vow, I activated the mod in Ghost mode, flew around my friend for a bit, returned to my body and my friend told me that my voice was coming from different places. Example: I'm standing in a warship and my voice came from the place where the rocket with goods lands.

**To Reproduce**
1. Activate Ghost mode.
2. You can choose any “target” (you or your friend for ghosting)
3. Fly around or even spawn a mob.
4. The problem has appeared.

**Expected behavior**
I just wanted to test the modification. This was our first launch. The same problem appeared on the Company planet (Gardion)

I wanted to return to my body, and I would like the voice to continue to come from my avatar.

**Screenshots**
No screenshots, sorry

**Mod version (please complete the following information):**
v1.0.7 by ControlCompany

**Additional context**

p,s That's my first bug report on GitHub, sorry if i made any mistakes. 

Best Regards.

**Comment by JustCallMeQuincy** [comment]
Did you have any other mods installed when this occurred?

**Comment by artemGAVxyliGUN** [comment]
> Did you have any other mods installed when this occurred?

Yes i am. I can share a file or a code of my Thunderstore profile.
Here's the code: 018d1ca7-a7d1-6887-5411-cd0e862e080f

**Comment by JustCallMeQuincy** [comment]
# Can you try the following steps?

(Assuming that you're using the r2modmanager or the Thunderstore)


## 1. In your profile, go to `Settings` → `Profile` → `Change profile`
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/f9f3cec1-1a82-469d-b579-285f1c6c8da6)

## 2. Click on `Create new`, name the profile (anything) and click on `Create`
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/a1714854-d439-4df4-a735-875f3c7e243a)
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/51d901aa-84d8-4e18-8e6f-3f0d329f270b)

## 3. Click on `Select profile` with the new profile selected
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/94aa5887-6d82-4e23-81e7-2da5731edb1d)

## 4. Go to the `Online` tab and install `ControlCompany`
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/27df1bbc-c963-436c-a79f-e0c0ea46c35a)
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/483b3e2c-60dc-4fe6-8f3d-d83957b23d23)

## 5. After installing, click on `Start modded`
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/b0473fcc-5662-4312-a856-9ee0e1947129)

**Comment by JustCallMeQuincy** [comment]
Closing this, assuming it's fixed without using other (incompatible) mods.
