### ISSUE TITLE
make the monsters dance that would be hilarious just Imagine

### ISSUE THREAD

**Issue by futtuXD** [ControlCompany/ControlCompany#111]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Additional context**

**Comment by JustCallMeQuincy** [comment]
Please next time fill out the form

**Comment by klampzlamps** [comment]
Oh I’m imagining alright, but it won’t be added to this mod. There are other mods that already do that, the focus of this mod is to control the monsters.

Another reason it won’t be added is that those emotes requires everyone in the lobby to have the mod installed which defeats the purpose of this mod.
