### ISSUE TITLE
Link to keybind configuration on controlcompany thunderstore

### ISSUE THREAD

**Issue by 4SSch33ks** [ControlCompany/ControlCompany#112]
The keybind configuration link does not work,when i click on the link i do not get redirected to the supposed website?

**Comment by JustCallMeQuincy** [comment]
Hi! The link leads to an *anchor* to the Keybinds section on the page

This one:
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/3eb2f2e8-034c-48a4-91ef-24f332e87a64)

**Comment by 4SSch33ks** [comment]
omg thanks bruh i was wondering why i wasn't redirected
