### ISSUE TITLE
Diversity Compat

### ISSUE THREAD

**Issue by ShadowmeC3** [ControlCompany/ControlCompany#115]
It would be awesome if as the bracken you could turn on and off the lights, or make their screen blue or make the roar noise.
Or as the girl (when you add) you could use the different voice lines, or take a player into a different instance.

It would be awesome please. (i have already asked the diversity creator too).

**Comment by klampzlamps** [comment]
Won’t be added to this mod, this mod is to simulate the existing monsters. Abilities can be added with other mods.
