### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Jboykin2000** [ControlCompany/ControlCompany#120]
i dont know how to find the BepInEx/config/ControlCompany.ControlCompany.cfg file can i get a step by step please

**Comment by koldunblshamanbl** [comment]
Configuration file is supposed to be created after pulling the lever to land on a moon, but I face the same problem - there is simply no such file in BepInEx/config. Also I can't hide UI by pressing 'u' button

**Comment by JustCallMeQuincy** [comment]
Since 1.0.8 the config should generate upon launching the game. Please ensure you're on the latest version

**Comment by JustCallMeQuincy** [comment]
@koldunblshamanbl could you please provide more information?

Are there any errors in the console?
Are you using any other mods? If so, have you tried without having other mods installed?

**Comment by Jboykin2000** [comment]
I found out where it is
