### ISSUE TITLE
Inverse teleporter ghost mode

### ISSUE THREAD

**Issue by masteryipp** [ControlCompany/ControlCompany#121]
**Describe the bug**
When Players went enter Inverse teleporter. When in ghost mode, the only monster that i can spawn as they entered the facility is the tree giant and monsters that are outside the facility. 

I suggest modify the code where when the players is in the facility. Monster that are avaliable can be controlled. Not when the player entered the entrance.

Mod version 1.1.0.

**Comment by JustCallMeQuincy** [comment]
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/32
