### ISSUE TITLE
Outside Darkness

### ISSUE THREAD

**Issue by PikachuGamer025** [ControlCompany/ControlCompany#122]
The mod works great and it seems really fun, but on some planets, for example Assurance, when I play as a monster outside, its really dark and hard to see. When I'm uphill I see fine, but when I'm downhill, the more shadowy parts are dark. Also when its night time, its alot worse

![20240120192428_1](https://github.com/ControlCompany/ControlCompany/assets/157256822/f9a0d219-be05-4ba2-9525-2790a74c24c0)
![20240120192445_1](https://github.com/ControlCompany/ControlCompany/assets/157256822/efab11cc-2b3e-4f43-865f-d33d86a61711)

If you could fix this part a little, that would be great

**Comment by klampzlamps** [comment]
This is a consequence of how the vanilla game behaves, for some reason when you spectate others the environment effects outside glitch out
