### ISSUE TITLE
Control the amount of credits received

### ISSUE THREAD

**Issue by Shpeven** [ControlCompany/ControlCompany#123]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Additional context**

**Comment by Shpeven** [comment]
It’d be cool and wouldn’t raise alarm to unsuspecting people

**Comment by JustCallMeQuincy** [comment]
Please next time fill out the form
Thanks for posting your idea!

**Comment by klampzlamps** [comment]
Since v1.1.1, Changed to +1000 per press instead of hard setting it to 5000 credits
