### ISSUE TITLE
Not being visible sometimes

### ISSUE THREAD

**Issue by OceC1apz** [ControlCompany/ControlCompany#129]
Im trying to use the mod but for some reason it just turns off mid game not showing the ui for monsters (yes i tried pressing u to see if it comes back and it didn't)
Idk how it happens or what causes this issue to occur but seems like switching moons or dying. I will try it later
It should show menu when you land but it shows it while the ship is going down but as soon as it lands it goes away
Ill try get some screenshots
Version is v1.1.0

**Comment by JustCallMeQuincy** [comment]
Are you using any other mods?

**Comment by OceC1apz** [comment]
yes

**Comment by JustCallMeQuincy** [comment]
Could you try to recreate the issue without running other mods?
