### ISSUE TITLE
Add back public lobbies with this mod

### ISSUE THREAD

**Issue by sivlare** [ControlCompany/ControlCompany#132]
It's not a huge problem to the overall gameplay, but I found real enjoyment out of slowly messing with random people in public lobbies with this. It's not that fun anymore in private lobbies where friends catch on very easily, ruining the "what is happening" thing the mod first approached by release, with it saying only you have to know. It's a small change, but I find making public lobbies again would make this more enjoyable.

Not to mention the "public griefing" part, where you can only do it on your own server. I don't see why you had to make it private only, when it takes 2 seconds to join a different lobby.

I'd like the situations where people were clueless as to what's happening, instead of my entire friend group being well-aware of the mod and what it's about. It's more funny seeing random people slowly figure it out or seeing their reactions when I tell them, Instead of it being in private lobbies where likely everyone knows, at least in my own experiences.

that's about it, really. I don't really think I'm the only one that thinks this change was unnecessary, and this probably won't even be acknowledged or re-implemented, but I wanted to voice my overall opinion and future request to add it back. I find the mod alot less enjoyable now that it's strictly in private lobbies.

**Comment by sword11247** [comment]
how can you even "grief" you own lobby????

**Comment by Lerrycapetime** [comment]
If people really don't like it, just find a server named "Non modded" or better yet host your own game, like holy shit, why this mod? Even if they did make it PRIVATE ONLY, we still got random hackers who join and instantly spawn shit or crash the game.
