### ISSUE TITLE
QoL Features

### ISSUE THREAD

**Issue by MrSpoon2005** [ControlCompany/ControlCompany#134]
**Is your feature request related to a problem? Please describe.**
This request is only related to certain QoL features I would like to see in the mod to make playing as the monsters more believable and fun.

**Describe the solution you'd like**
I would love to see a feature where killing someone as a monster freezes you until the animation is cleared, I noticed that with how it is currently, while killing someone you can just glide away even on accident and it looks goofy and gives away something is up. The second and last feature for QoL would be having the speed of the monster you are playing match the monster in game, currently when playing as something such as the Forest Keeper, you are not nearly as fast as an actual Forest Keeper, you are just as fast as your fellow crewmates.

**Additional context**
For the animation lock when killing, I don't think it would need to be active on ALL monsters, only the ones that typically can't move while doing so, such as Forest Keepers, Eyeless Dogs, and the Masked as some examples.

**Comment by klampzlamps** [comment]
Most of these are implemented with patches v1.1.3 and v1.1.4, closing issue
