### ISSUE TITLE
Masked spawning when using mod

### ISSUE THREAD

**Issue by Flailmorpho** [ControlCompany/ControlCompany#136]
Occasionally while using this mod, activating ghost mode seems to just, spawn a masked for some reason?? I'm not sure why this is happening but it makes it risky to fuck around with the mod on maps where masked aren't supposed to spawn.

**Comment by JustCallMeQuincy** [comment]
Please next time fill out the form.
Do you have any other mods installed?
Do you perhaps have a video of this bug occurring?

**Comment by oikaneda** [comment]
this is also happening with me too, RIGHT when they use the mod, a masked spawns. had 2 spawn back to back on vow. and then one outside on offense when we were leaving around 3 pm. and another outside on a map i dont remember. its so rare to see them on those maps i was so caught off gaurd xD

**Comment by klampzlamps** [comment]
Duplicate, closing in favour of #141
