### ISSUE TITLE
Make ghost mode and control mode work with performance mods.

### ISSUE THREAD

**Issue by Boxlock22** [ControlCompany/ControlCompany#139]
My computer is extremely slow and bad, I use multiple performance mods to make this game run smoothly, however, recently I decided to mess with the Control Company mod and figured out when entering ghost mod or control mode it disables the Performance mods until you exit these modes. While this may be an issue that cannot be fixed, I hope that it can be changed to support these performance mods.

P.S I can still technically use the mod, as I can run at around 6-12 FPS which is technically enough for me to be able to troll people. I just think adding support to Performance mods will be a sweet QOL change. This could also be cool for people who like using HDLethalCompany as it also disables the high-quality graphics when entering ghost mode or control mode.

**Comment by klampzlamps** [comment]
Update to v1.1.3 and try again, 1.1.3 should have optimized the camera rendering for ghost and monster modes.

**Comment by Boxlock22** [comment]
Thanks, I'll try it out!

**Comment by Boxlock22** [comment]
While I do notice slight changes to the performance it still doesn't keep the potato graphics that I have set with my performance mods.

**Comment by klampzlamps** [comment]
Full compatibility with performance mods has been released with v1.1.7. Closing issue.
