### ISSUE TITLE
Natural spawns no longer follow moon-specific restrictions

### ISSUE THREAD

**Issue by ascxk6** [ControlCompany/ControlCompany#141]
Description: Mobs that are only expected to spawn on later planets (Nutcracker, Masked) are spawning on earlier moons such as Assurance and Vow.

To reproduce: With Extended Mode off, enter Assurance and play as normal. Later in the day (past 7:00pm), a Masked may spawn near the ship and approach the back door.

Expected behavior: Regardless of what mobs are available for the player to spawn in as, natural mob spawns should occur only according to the spawn rates 

![image](https://github.com/ControlCompany/ControlCompany/assets/67481733/1204fc73-d97c-4f41-878c-d562dbdaf9d1)
Pictured: A Masked on the ship while in single-player non-extended mode

Version: v1.1.2

Additional context: No unusual mobs were seen spawning on early planets prior to v1.1.1.

**Comment by klampzlamps** [comment]
This is interesting, I don’t manipulate the spawn rates in any way but this isn’t the first report I’ve heard it happening. I’ll look into it, thanks!

**Comment by MGJerry** [comment]
I second this, have seen some Masked and rarely Nutcracker/Jester where they weren't supposed to be. At first I thought it could be because of LethalExpansion or BrutalCompany but nope, still happens after removal.

Version: v1.1.2, v1.1.3

**Comment by klampzlamps** [comment]
Ahh I was thinking about how this could be a possibility but looking back, yes this could happen because of the change in v1.1.2 which essentially allows the masked to be spawned anywhere.

Added to the list of changes in v1.1.4. Thanks for reporting this bug!!

**Comment by klampzlamps** [comment]
This should be fixed now, I've updated the mod to v1.1.4.
