### ISSUE TITLE
Ghost girl?

### ISSUE THREAD

**Issue by BreadYT** [ControlCompany/ControlCompany#143]
Will ghost girl ever make it as an experimental mob or is it not an entity that can be controlled? Seen it in the list of experimental monsters 2 weeks ago but yet to have seen it in the experimental menu.

**Comment by klampzlamps** [comment]
You can somewhat control the ghost girl using experimental mode + AI controlled. The ghost girl would most likely never make it to the stable list just because of the way the networking is done for her.
