### ISSUE TITLE
I used the Baboon Hawk (experimental feature i think) and when i changed to the player i can't do actions (can use the key E, can't change slots, etc

### ISSUE THREAD

**Issue by TomasFire2** [ControlCompany/ControlCompany#146]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Mod version (please complete the following information):**
You can find the version of the mod in the Thunderstore mod manager.

**Additional context**

**Comment by JustCallMeQuincy** [comment]
Please fill out the form next time.
Do you have any other mods installed?
