### ISSUE TITLE
почему когда я запустил хост пишет вот эту ошибку

### ISSUE THREAD

**Issue by Sersok1** [ControlCompany/ControlCompany#149]
произошла ошибка, когда игрок попытался подключиться к серверу!Перезапустите приложение и, пожалуйста, сообщите о сбое

**Comment by JustCallMeQuincy** [comment]
Please fill in the form next time.
Do you have any other mods installed?

**Comment by Sersok1** [comment]
нет

**Comment by JustCallMeQuincy** [comment]
Are you using r2modman to launch the game?
Are you trying to host your own lobby or are you trying to join someone else's?

**Comment by qwhjkdghqdjqwdhqwhdlqdqw** [comment]
내가 서버를 만들어서 누군가가 내서버에 들어올떄 서버가 꺼짐 누군가에 서버에 들어갈려할때 들어가지지가 않음
모드목록:
BeplnExPack
Morecompany
more_emote
cotrol company
skinwalkers

**Comment by JustCallMeQuincy** [comment]
> 내가 서버를 만들어서 누군가가 내서버에 들어올떄 서버가 꺼짐 누군가에 서버에 들어갈려할때 들어가지지가 않음 모드목록: BeplnExPack Morecompany more_emote cotrol company skinwalkers

I'm afraid that doesn't seem relevant to this mod specifically.

Ensure everyone has the same mods installed (not including ControlCompany).

**Comment by qwhjkdghqdjqwdhqwhdlqdqw** [comment]
오직 cotrol campant 와 morecampany BeplnExPack 만 적용시켰는데 아직도 누군가가 들어올때 로비가 강제종료가 됨

**Comment by klampzlamps** [comment]
This is unrelated to control company mod. It's most likely happening because either you or the person has other server-required mods. ControlCompany does not require anyone else to have the mod installed. It's actually purely client-side.
