### ISSUE TITLE
[Bug Report] Accidental leave vote

### ISSUE THREAD

**Issue by Magmabot16** [ControlCompany/ControlCompany#15]
When you're dead and controlling a monster, holding right click still votes to leave. This usually happens to me when playing the nutcracker and jester, I'll be holding down right click for the nutcracker's sentry mode and the jester's windup, and I'll accidentally vote for the ship to leave because I'm the only person who's dead.

**Comment by klampzlamps** [comment]
will be fixed in the next update! coming out tomorrow!

**Comment by klampzlamps** [comment]
Fixed with the release of v1.0.4, please update the mod through thunderstore

**Comment by Magmabot16** [comment]
sweet!
