### ISSUE TITLE
Aggro Form on Monsters

### ISSUE THREAD

**Issue by ZachFNF** [ControlCompany/ControlCompany#152]
add it soon please :D

**Comment by ZachFNF** [comment]
it would be really freakin fun  and i hope it comes soon

**Comment by JustCallMeQuincy** [comment]
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/78
Feel free to add more suggestions in that thread

**Comment by ZachFNF** [comment]
you wont add this?

**Comment by ZachFNF** [comment]
it said you closed it as "not planned"

**Comment by JustCallMeQuincy** [comment]
It's a duplicate, that's how those are closed
Refer to #78 on further developments on that request

**Comment by ZachFNF** [comment]
oh ok great thanks
