### ISSUE TITLE
Let the dead players take control of the monsters!

### ISSUE THREAD

**Issue by Amerize** [ControlCompany/ControlCompany#155]
Let the dead players take control of the monsters instead of just the host having control of the monsters at all times.

thx.

**Comment by klampzlamps** [comment]
You’ve asked the exact same question yesterday. As I’ve said in the other thread, this is not happening. #154

**Comment by Amerize** [comment]
Instead of building in a cool feature for all players, it's better to program a troll mod for one player...

**Comment by klampzlamps** [comment]
This has nothing to do with what you think is a “cool” feature or not.

I’m putting in my own time and effort in developing the mod and offering this mod for free.

You’re allowed to make requests and I’m allowed to reject requests which I don’t feel is worthwhile at this moment.
