### ISSUE TITLE
Full Movement Keybinds

### ISSUE THREAD

**Issue by BeauMarrow** [ControlCompany/ControlCompany#158]
I understand that the special keybinds for this mod are completely configurable within the config file for this mod, however, movement directions as well as sprinting are currently unbindable through the config and just remain the default binds. I use ESDF so I would much prefer the ability to either rebind these keys or to have them map to your in-game keybinds, as I see no reason why anyone wouldn't use their regular movement keybinds while controlling an entity.

I would love it if forward, backward, left, right, and sprint buttons were available to be bound in the config file (maybe even primary, secondary, and unique actions as well) or if they simply mapped to the player's regular keybinds that they have set, as opposed to the mod simply using default binds.

Thank you.

**Comment by klampzlamps** [comment]
Added a fix for next patch to use the in-game bindings for movement and sprint.

**Comment by JustCallMeQuincy** [comment]
Should be fixed as of v1.1.5
