### ISSUE TITLE
[Bug Report/Feature Request] Can't cross pits as monsters

### ISSUE THREAD

**Issue by Magmabot16** [ControlCompany/ControlCompany#16]
Currently when in creature control mode you just fall into pits when trying to cross. This makes it hard to chase down players and to be inconspicuous that you're actually controlling the monster.

**Comment by JustCallMeQuincy** [comment]
Same as https://github.com/ControlCompany/ControlCompany/issues/10

**Comment by Magmabot16** [comment]
Whoops didn't see that
