### ISSUE TITLE
Does not work online

### ISSUE THREAD

**Issue by stalk2223** [ControlCompany/ControlCompany#161]
Hello, the mod does not work in multiplayer. I create a room, I wait, people try to enter, but I get thrown into the menu and writes that an error occurred when joining the player.
Mod version: 1.14
Platform original game: Steam.

**Comment by ZachFNF** [comment]
This should not happen, Check if it is actually ControlCompany causing this or if its a different mod you have

**Comment by JustCallMeQuincy** [comment]
To add to ZachFNF's comment, 
please try to recreate this issue without any other mods installed
