### ISSUE TITLE
Can this mod randomly being in party ?

### ISSUE THREAD

**Issue by Alphetalon** [ControlCompany/ControlCompany#165]
I want to randomly turn into a monster with my friends. ( kinda like werewolf game )
So I came to ask in order to know whether it could be done or not.

Or there may be other mods that can do this.

PS.google translate

**Comment by JustCallMeQuincy** [comment]
I'm going to mark this as a duplicate for #2 as this will not be added.
Feel free to add your ideas in that thread though
