### ISSUE TITLE
Control the Company Monster?

### ISSUE THREAD

**Issue by Haravikk** [ControlCompany/ControlCompany#168]
Mostly as the title says, it would be funny if the host could gain "control" over the Company Monster, enabling them to cause the tentacles to spring out and grab players at the press of a button.

Probably isn't an actual monster though so it might need some more custom code to lock the camera on the counter and add button prompts to trigger it. And of course it shouldn't be spawnable. 😉

I also heard there were several other attacks the company can do that are in the game assets but not currently enabled; instead of tentacles there's an animation for a weird hand and a monstrous tongue as well, so maybe these could be options if there's a way to trigger them somehow?

**Comment by klampzlamps** [comment]
Sure why not. Planned for next release v1.1.6.
