### ISSUE TITLE
Dont touch me mod

### ISSUE THREAD

**Issue by HyperUndone** [ControlCompany/ControlCompany#169]
**Describe the bug**
A clear and concise description of what the bug is. -Attempting to back out of controlling the dont touch me button breaks the camera and doesn't allow you to return to player view

**To Reproduce**
-going into ghost mode and control the dont touch me button and attempt to return to player view

**Expected behavior**
-being able to return to player view after controlling any monster 

**Screenshots**

**Mod version (please complete the following information):**
You can find the version of the mod in the Thunderstore mod manager.
-ControlCompany: 1.1.5
-Dont touch me: 1.2.1

**Additional context**
-I can just copy paste the original question here.

"I wasn't sure where to ask this, but I wanted to know if compatibility was possible for the Don't Touch Me mod, i saw it was an available option when using Control Company and when I tried using it, it bugged out the game."

**Comment by klampzlamps** [comment]
Hi,

This will be fixed in the upcoming patch (v1.1.6). Thanks!

**Comment by klampzlamps** [comment]
Done. Released with v1.1.6
