### ISSUE TITLE
I don't have F1 on my keyboard 

### ISSUE THREAD

**Issue by VILLAIN100** [ControlCompany/ControlCompany#17]
Hi, can you please add a specific part where only host can see and where I can change keybind for things like Ghost Mode because I have a 60% keyboard

**Comment by JustCallMeQuincy** [comment]
Same as https://github.com/ControlCompany/ControlCompany/issues/5

**Comment by klampzlamps** [comment]
Fixed with the release of v1.0.4 (keybind config), please update the mod through thunderstore
