### ISSUE TITLE
Lobby Crash On Join

### ISSUE THREAD

**Issue by WiinterLass** [ControlCompany/ControlCompany#170]
I keep getting my lobby crashed the moment someone attempting to join my lobby. In which it tells me to report this issue.

**To Reproduce**
Clicking to join my multiplayer public lobby

**Expected behavior**
People to join my lobby without it crashing

**Screenshots**
![Screenshot (9)](https://github.com/ControlCompany/ControlCompany/assets/159852877/7c374344-d4ff-4435-b81f-1e8b87d4bb96)
**Mod version (please complete the following information):**

1.1.5v

**Additional context**
I am manual if this does make a difference.
![Screenshot (9)](https://github.com/ControlCompany/ControlCompany/assets/159852877/7c374344-d4ff-4435-b81f-1e8b87d4bb96)

**Comment by klampzlamps** [comment]
Since this is a client side mod it’s unrelated. Most likely you or the other person has another mod installed that’s causing the issue.

**Comment by WiinterLass** [comment]
> Since this is a client side mod it’s unrelated. Most likely you or the other person has another mod installed that’s causing the issue.

Any Ideas on what mods could be causing an issue?

**Comment by klampzlamps** [comment]
Nope, you'll need to disable mods one by one to see which one is the problematic mod.
