### ISSUE TITLE
не может зайти друг выкидывает с игры и пишет ошибку у обоих

### ISSUE THREAD

**Issue by bmdun** [ControlCompany/ControlCompany#174]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Mod version (please complete the following information):**
You can find the version of the mod in the Thunderstore mod manager.

**Additional context**

**Comment by JustCallMeQuincy** [comment]
Please fill out the form next time.
Do you have any other mods installed?

**Comment by klampzlamps** [comment]
Closing due to lack of response
