### ISSUE TITLE
Stuck in ghost mode

### ISSUE THREAD

**Issue by mousmouton** [ControlCompany/ControlCompany#175]
Hi, after I press f1 to enter in ghost mode, i'm stuck in it. When i click on escape it don't work and I can't become a monster. I'm just stuck in it and i'm forced to leave the game to escape from this. This is the error I get in the cmd 
![Capture d'écran 2024-02-16 182637](https://github.com/ControlCompany/ControlCompany/assets/160266744/e09408d0-f2ba-4cff-a196-0372d498c76c)

**Comment by JustCallMeQuincy** [comment]
Do you have any other mods installed?

**Comment by mousmouton** [comment]
No, I just have the control company mod and BepinEx
