### ISSUE TITLE
Copy HDLethalCompany graphics settings into the ghost mode cam.

### ISSUE THREAD

**Issue by broken-usb** [ControlCompany/ControlCompany#176]
**Is your feature request related to a problem? Please describe.**
Kinda, if you lower or increase the game's settings using HDLethalCompany(or any other similar mod), the ghost mode cam is still going to be with some of the default game's settings.

**Describe the solution you'd like**
If possible make so the ghost cam settings copies over the settings from HDLethalCompany to keep the graphics the same.

**Additional context**
Screenshot outside of ghost mode, i disabled a bunch of effects like post proscessing and shadow:
![1966720_20240217174535_1](https://github.com/ControlCompany/ControlCompany/assets/50057556/3f5feb3f-bf32-46b2-98d4-d1c4e9f41d38)

But when going into ghost mode those effects get reapplied:
(If i had also disabled the fog it would also get re-enabled)
![1966720_20240217174542_1](https://github.com/ControlCompany/ControlCompany/assets/50057556/f5a1fa0d-ee24-492e-af3e-0c58b7f4c050)

Also if you change your resolution with HDLethalCompany's resolution fix, changing into ghost mode will revert it back to the game's default 540p.

**Comment by klampzlamps** [comment]
Lets do it

**Comment by klampzlamps** [comment]
Done, released. Please update to the latest version
