### ISSUE TITLE
"[MODDED]" prefix ruining CC installed lobbies.

### ISSUE THREAD

**Issue by JUSABHFYABHD** [ControlCompany/ControlCompany#186]
All servers with the mod installed on the host's end now have the "[MODDED]" prefix applied to the server's name, without the host's consent.

It's a consistent occurrence when creating a lobby, even if you manually delete it, it will nonetheless appear in the title.

One of Control Company's main draws is the ability to use it to mess with your friends, without them knowing it is installed. This "feature" completely counteracts that premise.

v1.1.8

It's significantly harder to fill up lobbies with this bug. When I opened Lethal Company today, on one of the rare days that I had enough time to, I was excited to play. My discovery of this bug has sapped all of that drive from my being. There's already a mod to detect Control Company servers, so there is no need for this "feature"'s existence.

**Comment by JUSABHFYABHD** [comment]
This has been labeled as a bug because there is no possible way that a competent mod developer would willingly shoot themselves in the foot, like this. Once you've sobered up from whatever substance had influenced you to make this change, I hope that you will understand the severity of this bug, and subsequently fix it.

**Comment by JustCallMeQuincy** [comment]
This is a measure to mitigate trolling in public lobbies without the knowledge of others.

If you want to play with friends (as specified in your first comment), this is best done through a private lobby where the lobby name is not visible to the players joining.

**Comment by Nick56731** [comment]
i just want to play as a lootbug without having to wait 30 minutes for my public lobby to fill up pls

**Comment by JUSABHFYABHD** [comment]
But that doesn't matter, because CLEARLY every Control Company user is a malicious troll who needs to be filtered out of getting to play!!

**Comment by JUSABHFYABHD** [comment]
> i just want to play as a lootbug without having to wait 30 minutes for my public lobby to fill up pls

But that doesn't matter, because CLEARLY every Control Company user is a malicious troll who needs to be socially filtered out of getting to play!!
