### ISSUE TITLE
Reduce the given credit ammount

### ISSUE THREAD

**Issue by Vortal5555** [ControlCompany/ControlCompany#189]
The most fun way to use this mod is to mess with your friends in secret but if someone checks the terminal and sees 1000 extra credits the jig is up. 
It would be a lot easier to hide if you gave yourself a smaller amount and bought what you wanted. 
And if for some reason you want 1000 credits why not just give yourself 100 credits 10 times?

Ideally the fix for this would be to make the amount configurable but I'd take any lowering. I feel like I can't even risk going into the experimental mode because of the risk of adding 1000 credits and letting the cat out of the bag.

**Comment by klampzlamps** [comment]
Honestly the “give credits” and “teleport to entrance” functions were never supposed to be in the build and were used for testing purposes only. But it’s near impossible to take away something once you’ve given it so I guess they’re staying 🤷‍♂️

As for your concern, yeah I’ll add a keybind for the give credits and also reduce the amount.

**Comment by klampzlamps** [comment]
Released as part of v1.2.0
