### ISSUE TITLE
[Bug Report] Moons disappear from the terminal

### ISSUE THREAD

**Issue by smoluser** [ControlCompany/ControlCompany#19]
When typing "Moons" in the terminal, only the company building shows up. This seems to happen ONLY after pressing 8 for credits. It goes back to normal after rejoining the game, but it's not ideal. Might be important to mention I'm also running around 25 other mods, so something could be acting funky due to that. You can still travel to the moons by typing route and the name as normal, they're just invisible in the terminal. Tested many times and only pressing 8 for credits seems to do it. Also tried uninstalling the mod to make sure it wasn't something else.

EDIT: After hours of playing it just happens randomly lol
![screenie](https://github.com/ControlCompany/ControlCompany/assets/156474561/918a85ce-f590-49cf-b4c7-6be277f85313)

**Comment by JustCallMeQuincy** [comment]
I specifically tested this and it doesn't happen for me. I had a couple of unrelated mods installed during these tests.

Could you perhaps send the list of mods you were using?

**Comment by HoarderBug** [comment]
This looks like the same problem I'm coming across but it's with modded moons I think it has to do with use mods tho

**Comment by smoluser** [comment]
> I specifically tested this and it doesn't happen for me. I had a couple of unrelated mods installed during these tests.
> 
> Could you perhaps send the list of mods you were using?

![image](https://github.com/ControlCompany/ControlCompany/assets/156474561/bb1d0bbe-8787-42aa-a5b1-7a460410471b)
![image](https://github.com/ControlCompany/ControlCompany/assets/156474561/d687c660-de0c-44d1-be57-f4cc2c25cbf0)
![image](https://github.com/ControlCompany/ControlCompany/assets/156474561/555e2e8d-fcb6-4488-a793-ae77d49b0117)

It appears I was in fact using a modded map, so thats my bad </3 I forgot about the SCP dungeon mod
So here's my modlist, 31 in total

**Comment by JustCallMeQuincy** [comment]
Since it happened on a modded map, I think we can mark this a `other mod compatibility`
Though I suspect the priority for this to be quite low

**Comment by smoluser** [comment]
> Since it happened on a modded map, I think we can mark this a `other mod compatibility` Though I suspect the priority for this to be quite low

If by modded map u mean the modded facility generation, it didn't. It just happened naturally in normal moons with normal facilities. In fact we never even got the SCP map generation in any of the runs we did. Tho yeah I agree it's really no big issue, gameplay is literally not affected by it at all so long u remember the moon names haha I just wanted to bring it up so it would be something that's at least known

Have a lovely day 💕
