### ISSUE TITLE
Is it possible to highlight players when in monster mode

### ISSUE THREAD

**Issue by Whit3Creeper** [ControlCompany/ControlCompany#193]
This is a feature request.
Can you add player highlights which is when the player is in monster mode. They can see players highlighted which can be seen through walls. This feature allows the players to see where the player is going and can allow players to sneak attack them, for example Brackens (Flowerman) and Forest Keepers (Forest Giants). There are problems for players when controlling the Forest Keepers is hard to see where the players are at like in the map Vow and March with a tons of trees. So, adding highlights to players are a good suggestion so that the controller doesn't have a hard time to find players when they are in search of players to troll.

If this suggestion cannot be done, then is fine. At the very least, I suggested something :)

**Comment by Ishdhd** [comment]
Agreed!
