### ISSUE TITLE
Can't control any mob

### ISSUE THREAD

**Issue by Grosfilsdep** [ControlCompany/ControlCompany#195]
Hi, sorry for my bad english in advance

I just installed the new version of the mod. When I press F1, I enter in ghost mode but I don't have any option to become a mob. When I press f1-f2-etc... nothing happen.

**Comment by JustCallMeQuincy** [comment]
Hi!

Could you try editing the keybind to toggle the menu to a different key, then try again?

If this doesn't work, please try this without any other mods enabled.

**Comment by JustCallMeQuincy** [comment]
Closing this issue due to lack of response.
Feel free to re-open this issue if you find the time to try my suggested fixes
