### ISSUE TITLE
Take-off and landing will result in pushbutton calls turning into anytime calls

### ISSUE THREAD

**Issue by 1410677474** [ControlCompany/ControlCompany#196]
As the title says

**Comment by JustCallMeQuincy** [comment]
Hi!
Do you perhaps mean push-to-talk (instead of pushbutton calls) and voice-activation (instead of anytime calls)?

**Comment by 1410677474** [comment]
yes



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 22, 2024 07:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ControlCompany/ControlCompany] Take-off and landing will resultin pushbutton calls turning into anytime calls (Issue #196)




 
Hi!
 Do you perhaps mean push-to-talk (instead of pushbutton calls) and voice-activation (instead of anytime calls)?

**Comment by klampzlamps** [comment]
Fixed
