### ISSUE TITLE
고스트 모드일때 보이는 모습

### ISSUE THREAD

**Issue by pil0lo** [ControlCompany/ControlCompany#197]
Why does the image look like a photo in ghost mode?

When I went into ghost mode
My friend says it looks normal.
Why do I look like this?

![1](https://github.com/ControlCompany/ControlCompany/assets/143984023/a4a8815b-8376-4eef-848e-e0ecc6ed2d80)

**Comment by klampzlamps** [comment]
It’s the games LOD (level of detail). Only you can see it, this is how the player model looks like on the outside while you’re playing the game.

**Comment by klampzlamps** [comment]
Not a bug.

**Comment by pil0lo** [comment]
How do I set it so that my entire appearance is visible when in ghost mode?
Is it possible to display your character in its entirety?

**Comment by JustCallMeQuincy** [comment]
From a certain distance, your full character will appear (if I recall correctly)
