### ISSUE TITLE
Error with the f keys

### ISSUE THREAD

**Issue by adam77788** [ControlCompany/ControlCompany#200]
Faced with the problem that in the flying company, many keys f1,f2,f3,f4 do not work ....... and all the keys that contain f , is it possible to replace this key with some other so that people who have this error can use the mod?

**Comment by klampzlamps** [comment]
Look in the config.

**Comment by adam77788** [comment]
Can't you just change f1 to another key instead?

**Comment by klampzlamps** [comment]
You can change that in the config, please read the mod description page fully. It’s a problem with your specific keyboard so it doesn’t make sense to change the default config for everyone.
