### ISSUE TITLE
Curious

### ISSUE THREAD

**Issue by BandeeDee** [ControlCompany/ControlCompany#203]
Not tryna rush anyone or anything, just curious, but I hope everythings going well with y'all on the development team. noticed that there hasn't been much activity and just was wondering when the next update would happen.

the mods been so fun and i would love to see whats next, thank you :)

**Comment by klampzlamps** [comment]
I’ll put out an update for v50 of the game some time within the next 2 weeks. The “team” is just me and I’ve been busy with several other projects lately 😂

**Comment by BandeeDee** [comment]
Understandable. excited for the update then!

**Comment by klampzlamps** [comment]
Patch v1.3.0 has been released which adds control functionality to the Old Bird
