### ISSUE TITLE
Adding the new monsters (Klampzlamps did not help me and left me without even trying to fix the issue)

### ISSUE THREAD

**Issue by YourLocalWorm** [ControlCompany/ControlCompany#204]
I would really enjoy if more than just the rad mech was added to control company as of the V50 update to Lethal Company, was very dissapointed I could not play as the new butler or tulip snakes. 

Of course no rush on your part but pretty pleaseeeee

**Comment by klampzlamps** [comment]
Patch v1.3.0 has been released which adds control functionality to the Old Bird, also you can play as the Butler if you enable extended mode (press 0 while in ghost mode)

**Comment by YourLocalWorm** [comment]
> Patch v1.3.0 has been released which adds control functionality to the Old Bird, also you can play as the Butler if you enable extended mode (press 0 while in ghost mode)

I have launched the mod and cannot find the butler sadly, did I do something wrong?

**Comment by YourLocalWorm** [comment]
![LCcontroloutside](https://github.com/ControlCompany/ControlCompany/assets/167016397/778e1cff-2e06-4518-bbdd-4fd6e4f10b89)
![LCControlCinsidenormal](https://github.com/ControlCompany/ControlCompany/assets/167016397/b449faef-46b0-4078-953a-f3bb73ab68b3)
![LCControlCinside0](https://github.com/ControlCompany/ControlCompany/assets/167016397/a9d3c455-9de5-42cd-a565-4c122a0308b3)

**Comment by YourLocalWorm** [comment]
@klampzlamps Sorry if I am bothering you but I am still unsure if it's a glitch only for me

**Comment by YourLocalWorm** [comment]
please fix the mod  bro ur leaving me hanging ;-;

**Comment by klampzlamps** [comment]
you gotta be in a level where the butler normally spawns (e.g. Titan)
