### ISSUE TITLE
A bug with where I/You spawn when you become a monster using Control Company on any moon inside any interior

### ISSUE THREAD

**Issue by Birds0503** [ControlCompany/ControlCompany#212]
**Describe the bug**: 
I don't know if this is a bug, new update or something meant to be there but usually I would've become the monster where I was in Ghost Mode but for some reason now I spawn next to a vent like the AI enemies do. If this is a feature then ok but I'd like it to be changed back, if this is a bug then I'd love for it to be fixed and if I'm the only person this is happening to then I'm confused and will check when ever is needed to be checked. Thank You!

**To Reproduce**:
Just pick a monster and become it and see where you end up

**Expected behavior**:
You spawn as the monster where you were in free cam/Ghost Mode

**Mod version (please complete the following information):**
v1.2.4 - Newest Version from when I Submit this Issue

**Additional context**:
Thank You for making this mod to begin with its very fun but again has a few bugs that I'm excited to see FIXED!

**Comment by DeadShot187xx** [comment]
Possibility you have the config for natural enemy spawn locations on?

**Comment by DeadShot187xx** [comment]
^^^

**Comment by Birds0503** [comment]
Yes I had and didn't realise it thank you for helping though, much
appreciated!
