### ISSUE TITLE
Teleporting back to Ship using the "9" key

### ISSUE THREAD

**Issue by Birds0503** [ControlCompany/ControlCompany#215]
**Is your feature request related to a problem? 
No, I just think it would be useful.

**Describe the solution you'd like**
I think that when you press "9" to teleport the entrance it should make it so you can just press 9 again while inside facility to teleport back to ship.

**Additional context**
I also think that Kidnapper Fox should be added into the experimental monsters area but I know its being worked on so take however amount of time you need.

**Comment by klampzlamps** [comment]
No plans to add teleport to ship function, as for the kidnapper fox I added it in the latest patch as experimental
