### ISSUE TITLE
Hello, tell me what to do if the keys do not work: f1,f2,f3 and so on (I can't become a monster)

### ISSUE THREAD

**Issue by Cubecomp** [ControlCompany/ControlCompany#216]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Mod version (please complete the following information):**
You can find the version of the mod in the Thunderstore mod manager.

**Additional context**

**Comment by klampzlamps** [comment]
Wait the config file to change your keys

**Comment by Cubecomp** [comment]
How long do I have to wait? I tried to change the control keys but it doesn't work
