### ISSUE TITLE
[FEATURE REQUEST] We need button to disable mod interface

### ISSUE THREAD

**Issue by Nekropl** [ControlCompany/ControlCompany#22]
I often record clips of funny moments when we play with friends, I am the host and because of the constant mod interface I can't record clips again since they will guess that I control mobs).

**Comment by klampzlamps** [comment]
yep coming in the next update tomorrow!

**Comment by klampzlamps** [comment]
Fixed with the release of v1.0.4, please update the mod through thunderstore
