### ISSUE TITLE
Seeing players through the map

### ISSUE THREAD

**Issue by LethalValley** [ControlCompany/ControlCompany#225]
After using the mod player could see other players as Red figures after using the shop in game.
Sometimes whole bodies would disappear and not be visible to other players.

Sometimes it happened after using the shop, other times it didn't.

Mod version for control company is v1.3.2
Mod version for Control company filter is v1.0.0

It is possible that this problem may be caused by the control company addons mod by TestAccount666. May be worth looking into.

This is a link to a clip showing the problem of Red Players
https://medal.tv/games/lethal-company/clips/ixAzat47de9RbKKQp/d1337748k6xT?invite=cr-MSw4YXosMTg4MzI4NzY1LA

**Comment by klampzlamps** [comment]
This is unrelated to ControlCompany, the mod doesn't affect player models/shaders whatsoever. I would say it's most likely due to the addon mod.
