### ISSUE TITLE
New Spawn Mode For Realistic Spawning

### ISSUE THREAD

**Issue by B0nesRC0ol** [ControlCompany/ControlCompany#233]
**Describe the solution you'd like**
A New mode that allows you to switch between vents in the facility, and spawn monsters from them. Perhaps this could be done in a way such that your screen resembles the monitor on the ship, but you can move around freely and select highlighted vents to spawn from. (Would probably require a lot of time and effort to implement, not really expecting this to be considered but it would be a cool feature!)

**Comment by klampzlamps** [comment]
There's a config setting which changes spawn mode from "ghost mode" to a random vent
