### ISSUE TITLE
Friends cant join my CC lobby

### ISSUE THREAD

**Issue by Deathgun2208** [ControlCompany/ControlCompany#234]
Everytime I try to troll my friends with control company the problem is they cant join when I have the mod installed, they just get an error

**Comment by aplleman309** [comment]
I am also having the same bug

**Comment by klampzlamps** [comment]
You probably have other mods that interfere. Control company doesn't add anything for anyone else except for players with the mod so it shouldn't interfere.

**Comment by aplleman309** [comment]
Do you have any idea as to what other mods could interfere, or a type of mod
