### ISSUE TITLE
Monsters despawn after leaving their pov

### ISSUE THREAD

**Issue by bobbiiiii** [ControlCompany/ControlCompany#236]
**Describe the bug**
basically when i press escape to leave ghostmode, then the monster i controlled despawns immediately. that also occurs if i let the AI take control before pressing esc. 

**To Reproduce**
1. Spawn an entity.
2. let AI control
3. Press esc

**Expected behavior**
I expected, that the monster i spawned would still roam around in the facility or outside.

**Screenshots**
its hard to screenshot something that doesnt exist 

**Mod version (please complete the following information):**
ControlCompany-ControlCompany-1.3.2 (latest version)

**Additional context**
maybe its bc im missing other mods, but ive seen on youtube others have used it and the monster would still walk around, and they havent used other mods.

**Comment by klampzlamps** [comment]
That feature is another mod which works on top of control company.
