### ISSUE TITLE
I can"t open the extented mode

### ISSUE THREAD

**Issue by Nihilus57** [ControlCompany/ControlCompany#24]
Hello guys,
Firstly, thank you so much to have made such a wonderful mod for us.
Although, I can't open the extented mode with 0, i have an AZERTY keyboard.. Do you know how can I fix this ?
Thanks

**Comment by JustCallMeQuincy** [comment]
Make sure you land on a moon first, then pressing 0 will show the other keybinds in the top right corner

**Comment by Nihilus57** [comment]
> Make sure you land on a moon first, then pressing 0 will show the other keybinds in the top right corner

Yes, i already do that ^^

**Comment by Nihilus57** [comment]
and i have not pressed the "VerrNum" key

**Comment by JustCallMeQuincy** [comment]
I'm afraid you'll have to wait for the update tomorrow to change your keybind, since AZERTY doesn't have 0 without pressing shift.

**Comment by JustCallMeQuincy** [comment]
Until then you could probably change your keyboard layout in Windows to QWERTY

**Comment by Nihilus57** [comment]
Ah you mean this 0 ? I thought the one at the right of the keyboard, where there is a square of numbers

**Comment by Nihilus57** [comment]
> Until then you could probably change your keyboard layout in Windows to QWERTY

yes i did windows +space

**Comment by Nihilus57** [comment]
okay ! it does work, i've pressed the 0 on the top of the keyboard in QWERTY, thanks !

**Comment by JustCallMeQuincy** [comment]
Lovely! You can close this issue :D
@nihilus57

**Comment by klampzlamps** [comment]
Fixed with the release of v1.0.4 (keybind config), please update the mod through thunderstore
