### ISSUE TITLE
Make it please at mod

### ISSUE THREAD

**Issue by Rutga** [ControlCompany/ControlCompany#26]
Make it so that you can control: bracken, coil head, Big dog, and make beetles and other monsters make sounds on button 9 and emotions on 8 7 6 5 for monsters (depending on if there are emotions and how many of them)

**Comment by JustCallMeQuincy** [comment]
You can already control all of those monsters, for as long as they're able to spawn in the area that the selected player's in.
Ability to make sounds: https://github.com/ControlCompany/ControlCompany/issues/12
Keybinds configuration: https://github.com/ControlCompany/ControlCompany/issues/5

**Comment by klampzlamps** [comment]
closing in favour of the other issues, as for keybind config it has been fixed with the release of v1.0.4, please update the mod through thunderstore
