### ISSUE TITLE
Stuck as Monsters

### ISSUE THREAD

**Issue by AcidicSFX** [ControlCompany/ControlCompany#27]
When I played last night, I'd spawn as a monster, but when hitting the ESC key, nothing happens, I can only change monsters. To fix this, I had to have said monster go up to my body and kill it. Making friends think that the game found me and the monster took me out. I'm not sure if this is an issue for others as well.

**Comment by JustCallMeQuincy** [comment]
Is it possible to test this without any other mods installed, and perhaps recording it if possible?
I feel like that could help show what exactly is going on

**Comment by JustCallMeQuincy** [comment]
Closing this for now. You can re-open this if you've done further testing.
