### ISSUE TITLE
Coil heads and bracken issue

### ISSUE THREAD

**Issue by Nihilus57** [ControlCompany/ControlCompany#28]
Hello, 
As i saw, we can't play the coil head yet, is it just a bug or no ? 
And concerning the bracken, when i stand up with him, when someone sees me, is there a way to crouch again to stalk players ?

**Comment by JustCallMeQuincy** [comment]
These monsters are still experimental, so further functionality will be added in future released.
You can always suggest functionalities that you could like to see in a Feature Request here in the Github

**Comment by Nihilus57** [comment]
Okay no problem.
So we can't crouch with the bracken without despawning him and respawn if i understand well ?

**Comment by JustCallMeQuincy** [comment]
He crouches automatically, in my experience
Probably based on the AI

**Comment by Nihilus57** [comment]
okay

**Comment by Nihilus57** [comment]
and concerning the lasso, what is he ?? A monster provided for further versions ? I cant kill anyone with him for the moment

**Comment by HoarderBug** [comment]
> and concerning the lasso, what is he ?? A monster provided for further versions ? I cant kill anyone with him for the moment

The laso man is a mob that zeekers put in the game if you see it vanilla call yourself lucky they don't hurt player is can gard you with there hotbox 👍

**Comment by klampzlamps** [comment]
closing in favour of #37
