### ISSUE TITLE
Play as the mask

### ISSUE THREAD

**Issue by CatoVR** [ControlCompany/ControlCompany#29]
I really wanna play the mask and with the MaskedEnemyOverhaul mod in order to still look the same and talk to my teammates but then just kill them >:3 
It would be super cool if you could make it that one has the respected cosmetics like the Mask in the Mod I named and possibly even still show the Username perhaps xD

**Comment by CatoVR** [comment]
I just tested and see that I can use the mask on Rend, however I would like to be able to use it everywhere aswell like in the named Mod

**Comment by klampzlamps** [comment]
closing in favour of #37
