### ISSUE TITLE
different ghost movement

### ISSUE THREAD

**Issue by CREEPERDUDE062** [ControlCompany/ControlCompany#3]
would be cool if there was a teleport inside as a option. or ghost mode can climb ladder and enter doors

**Comment by klampzlamps** [comment]
If you enable extended mode (0 key) you can teleport your player inside the factory, or are you referring to the ghost mode teleporting?

**Comment by JustCallMeQuincy** [comment]
I think that having the ability to teleport inside as a ghost while leaving your player where it is could be a nice addition.
