### ISSUE TITLE
Thumper AI is bugged

### ISSUE THREAD

**Issue by HoarderBug** [ControlCompany/ControlCompany#30]
This might be happening because I have lethal escape
But the thumper will "move" but will be standing still and if I jump into AI mode it teleports to a different location

**Comment by JustCallMeQuincy** [comment]
I personally haven't had that issue without running other mods

**Comment by JustCallMeQuincy** [comment]
In my testing the Thumper AI works as expected, though there are some Dsync issues

**Comment by Magmabot16** [comment]
I've had the same issue happen to me before where I'll turn ai on, turn it back off, go somewhere else and turn ai back on and it'll teleport to a different location as if it had be wandering around separately while I was controlling it

**Comment by JustCallMeQuincy** [comment]
> I've had the same issue happen to me before where I'll turn ai on, turn it back off, go somewhere else and turn ai back on and it'll teleport to a different location as if it had be wandering around separately while I was controlling it

@Magmabot16 these issues should now be fixed (my limited testing has confirmed this)

**Comment by klampzlamps** [comment]
fixed as of v1.0.6

**Comment by Magmabot16** [comment]
Just had the same bug with jester where turning on the ai teleported it to a different spot

**Comment by klampzlamps** [comment]
Did you update the mod to v1.0.6+?

**Comment by Magmabot16** [comment]
yes

**Comment by Magmabot16** [comment]
on v1.0.7
