### ISSUE TITLE
Bracken Attacks Players Automatically

### ISSUE THREAD

**Issue by Withergaming101** [ControlCompany/ControlCompany#31]
I understand that the Bracken is in Experimental for a reason, but I found a huge issue: He killed a player without me telling him to. I dont know how, but my friend walked by me as I was sneaking up on him and without any input, snapped his neck.

**Comment by JustCallMeQuincy** [comment]
Right now it's a "contact" kill, pretty sure that this will change once the Bracken has been properly implemented (still experimental)

**Comment by klampzlamps** [comment]
This will be fixed in the next update (v1.0.5), no release date yet but it is a priority to move Bracken to the stable monster list.

**Comment by klampzlamps** [comment]
closing in favour of #35
