### ISSUE TITLE
Spore Lizard Desync

### ISSUE THREAD

**Issue by Autumnis** [ControlCompany/ControlCompany#36]
The spore lizard seems to have alot of desync for players. When switching between AI and player control it sometimes warps around, seeming that there's basically two spore lizards on the map. I don't know how it looks to other players, but they briefly commented on it then acted like it wasn't there.
This same desync also applies to eyeless dogs, but I will cut them a ribeye of slack since they're experimental.

**Comment by JustCallMeQuincy** [comment]
I also experienced this

**Comment by klampzlamps** [comment]
Should be fixed since v1.0.6
