### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by YuroKashine** [ControlCompany/ControlCompany#4]
Hi!

I have a request for a really fun feature.
I have been waiting for a mod like this and what would be really cool would be the following:

A function that where if someone has died they can become a random creature on the map.

That way when someone dies they can choose to become a random creature to hunt their friends for fun or scare them. and it would be nice if it is one random creature thats picked so that people can't cheese the game by for example becoming a spider when someone is being chased by one. This way people that have died can have some fun hunting their teammates with a random creature selected for them.

**Comment by klampzlamps** [comment]
Hey thanks for requesting this feature! I already have something like this in the works, but more to be revealed later!

Right now I’m focused on implementing all the other monsters, but I’ll be sure to have something similar to this in a major update!

**Comment by YuroKashine** [comment]
Amazing!!

Thank you so much.
Literally last week and im not kidding... i was looking between all the mods for one that makes you able to control monsters. I have literally been looking for something like this hahaha so glad someone read my mind

**Comment by YuroKashine** [comment]
I think the mod is broken for me. :( i just tried using it to scare my friend but its being very weird. i could spawn a giant on me... so he said ohhh theres a giant on top of that rock... meanwhile i was already in his face and i couldnt even eat him. but he still saw me on top of that rock... so when i went back to ghostmode and put the giant into AI he immideately ate me... so what i saw in my client was totally different from what he saw and what happened. plus the monster in my client was unresponsive with his abilities and actions.

Furthermore, i did one run solo and changed into the headhugger centipede.. but that was a little buggy too ... it did an animation to stick on the roof but then it just got stuck on the ground and i couldnt do anything anymore.

This is the code to the modpack im using:
018cff2e-65e3-9425-28ec-76e697e67ba2

**Comment by klampzlamps** [comment]
The de-sync issues should be fixed with v1.0.7 (latest release as of Jan 14)
