### ISSUE TITLE
Mod does not work whatsoever through Thunderstore

### ISSUE THREAD

**Issue by AxilotlX** [ControlCompany/ControlCompany#40]
I dont know the inital cause, but downloading it through thunderstore entirely does not work. the small bit of UI doesnt show up, the buttons dont work, I tried getting LethalConfig to see if its even detected but not even that loaded at all.

**Comment by JustCallMeQuincy** [comment]
I use this mod through Thunderstore and it works as expected.
Make sure you land on a moon, since that's when the menu appears.

**Comment by AxilotlX** [comment]
ive landed and Ive been playing with a friend, so it works for him on his save file, but for me it just, well, doesnt work even after landing.

**Comment by AxilotlX** [comment]
(I've tried re-enabling the UI with U and that also doesnt work)

**Comment by JustCallMeQuincy** [comment]
Can you send a list of active mods?

**Comment by AxilotlX** [comment]
![image](https://github.com/ControlCompany/ControlCompany/assets/136022383/5a1ffc0f-5aca-489b-b97f-1c6e972c8440)

**Comment by AxilotlX** [comment]
blank modpack with just BepInEx and ControlCompany

**Comment by Xterial** [comment]
<img width="668" alt="image" src="https://github.com/ControlCompany/ControlCompany/assets/156545887/4bdf1c0a-b188-4d37-b35f-c01695c8476f">

this is what the log sends me

**Comment by MartinPJB** [comment]
> <img alt="image" width="668" src="https://private-user-images.githubusercontent.com/156545887/296515619-4bdf1c0a-b188-4d37-b35f-c01695c8476f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxODI0MDIsIm5iZiI6MTcwNTE4MjEwMiwicGF0aCI6Ii8xNTY1NDU4ODcvMjk2NTE1NjE5LTRiZGYxYzBhLWIxODgtNGQzNy1iMzVmLWMwMTY5NWM4NDc2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QyMTQxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGUyN2Q5Y2JiNGQwMTEwNzY2YTdkNTkxYTVmMTdhNmFiNDIwZmIyMTRhMzQyODA2NGMwMWQyMjRkZjgxN2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rtqtiz4cg1WQFimEult_3QWH_cHlvibZo9-3Q-U6txE">
> this is what the log sends me

Same situation for me, the mod isn't working, same error in the logs.

**Comment by klampzlamps** [comment]
Hi, could you try installing the previous version (v1.0.3) and trying again? Thanks!

**Comment by klampzlamps** [comment]
The latest version fixes some issues with the keybind config so please give it a try and let me know :)  (namely different keyboard layouts may be introducing incorrect binds)

**Comment by JustCallMeQuincy** [comment]
I think this can be closed for the time being
