### ISSUE TITLE
[BUG] the mod isnt working

### ISSUE THREAD

**Issue by Xterial** [ControlCompany/ControlCompany#42]
this is the message that thunderstore log gives me every single milisecond spamming it consistantly:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ControlCompany.Core.ControlCenter.InputUpdate () (at <518eb8a9d57349c989a669c57f3c20df>:0)
ControlCompany.Core.ControlCenter.Update () (at <518eb8a9d57349c989a669c57f3c20df>:0)

**Comment by klampzlamps** [comment]
Hi, please update to the latest version v1.0.5 and try again. Thanks!
