### ISSUE TITLE
i cant move while in ghost mode

### ISSUE THREAD

**Issue by golico** [ControlCompany/ControlCompany#44]
the ghost mode still works perfectly fine but i cant move or look around. Other friends have the same issue

**Comment by klampzlamps** [comment]
Which version of the mod are you using? I just released v1.0.5, can you the latest version? Thanks!

**Comment by golico** [comment]
> Which version of the mod are you using? I just released v1.0.5, can you the latest version? Thanks!

i was using 1.0.4 but as soon as i can ill update it, thanks for the quick reply

**Comment by golico** [comment]
Ok ghost mode works normally now thank you

**Comment by klampzlamps** [comment]
Perfect! Thanks for reporting the issue, this is something that was a miss on my part (different keyboard layouts caused the keybind config to fail)
