### ISSUE TITLE
No menu in ghost mode, unable to exit enemies, and attack enemy mode on Proton Linux

### ISSUE THREAD

**Issue by AshDab119** [ControlCompany/ControlCompany#45]
I am unable to leave both ghost mode and enemy mode in Proton Linux. I have tried to use a different version of Proton and disable mods, though nothing seems to fix the issue. I also have tried to lower my resolution due to me owning a wide-screen, but no luck.

**Comment by klampzlamps** [comment]
Hi, I’ve recently updated to v1.0.5 which may fix this issue, I suspect it may be due to keybinds. In any case you can now configure keybinds to leave ghost and enemy mode (see mod page for details)

**Comment by AshDab119** [comment]
Though, the menu when going into both modded modes disappears for unknown reasons. I'm going to update now to see if that fixes the issue.

**Comment by AshDab119** [comment]
The new update has fixed the issue. Thank you for helping with my issue and have an amazing day!
