### ISSUE TITLE
how to reach configs?

### ISSUE THREAD

**Issue by YuroKashine** [ControlCompany/ControlCompany#49]
Hi its me again.

I saw that you added configs for the keybinds.
I would love to know where they are because i cant see it in the ingame options neither in the mod manager options. i really want to bind some of the functions to different keys since for example 8 is an emote... and i now very often accidently clicked 0 and then 8 and give myself 5000 credits which basically ruins the whole run if youre trying to play seriously.

**Comment by YuroKashine** [comment]
Also i would love for there to be configs to maybe filter which functions i want on and off... like the 5000 credits thing, if possible :)

**Comment by JustCallMeQuincy** [comment]
All configs are located in `BepInEx\config\` after running the game at least once with the mod installed.
