### ISSUE TITLE
[Request] Keybind Configuration

### ISSUE THREAD

**Issue by RegularPerson** [ControlCompany/ControlCompany#5]
For the sake of not conflicting the default keybinds with mods like MoreEmotes, the ability to either change keybinds via config file or in-game settings.

**Comment by prosthetis** [comment]
_adding comment for creator to see_

i second this. been trying to activate extended mode and it doesnt seem to want to work. i do have a tkl keyboard, but have been trying to use windows on screen keyboard to activate it. would be a blessing to have them be changeable.

got a friend to try using the extended mode as well and he has a 0 numkey, wasn't working for him either.

**Comment by Holtigo** [comment]
Bumping, this is really one of the most important things that this mod needs, is a CFG file to edit the key binds. Would be a great quality of life update.

**Comment by klampzlamps** [comment]
This is my highest priority right now and will be released with the next update! Thanks all!

**Comment by klampzlamps** [comment]
Fixed with the release of v1.0.4, please update the mod through thunderstore
