### ISSUE TITLE
Feature Request: Add the ability to ignore spawning conditions when in experimental mode

### ISSUE THREAD

**Issue by Kelkios** [ControlCompany/ControlCompany#50]
As put in the title, when you press 0 as a player you would be able to spawn masked on any moon, as well as possibly adding the ability to spawn inside monsters outside and vice versa.

I understand the complications with the AI outside, but it may be easier to lock this ability to experimental mode for this reason

Also possibly adding the ability to spawn monsters on The Company Building? Or atleast be able to control Jeb in some way?

**Comment by Kelkios** [comment]
Just a possibility for some future releases, don't want to put any burden on development

**Comment by JustCallMeQuincy** [comment]
This would be very nice indeed

**Comment by klampzlamps** [comment]
The company monster and masked was added a couple patches ago, closing.
