### ISSUE TITLE
Red text for other players

### ISSUE THREAD

**Issue by JaceB99** [ControlCompany/ControlCompany#53]
For people without the mod, it says in the top left "Not hosting. control company mod is disabled". Ruins the surprise, any way to turn that red text off?

**Comment by klampzlamps** [comment]
That’s shouldn’t be possible unless they have the mod as well.

**Comment by JustCallMeQuincy** [comment]
I tested this and only if non-hosts have the mod installed, this text shows up. Not if they don't (that wouldn't be possible)
