### ISSUE TITLE
[Feature request] Hide red text

### ISSUE THREAD

**Issue by IpNbeFkZqxd3Mb** [ControlCompany/ControlCompany#57]
I hope there was an option to hide the red text

**Comment by klampzlamps** [comment]
Do you mean the text when you’re not hosting?

**Comment by IpNbeFkZqxd3Mb** [comment]
yes and i want to hide it

**Comment by klampzlamps** [comment]
Snuck it in for the next update v1.0.6 which should be releasing in the next few hours 😁

**Comment by IpNbeFkZqxd3Mb** [comment]
that was awesome:)

**Comment by JustCallMeQuincy** [comment]
Completed in V1.0.6
