### ISSUE TITLE
R2Modman not recognizing the mod at all

### ISSUE THREAD

**Issue by Existingperson26** [ControlCompany/ControlCompany#58]
I have the mod updated to 1.0.5, BepInEx is up to date and installed, and i only have three other mods, being better teleporters and bodycams. Nothing is showing up in the config editor like it doesn't even know the mod is there in the first place. Any help?

**Comment by JustCallMeQuincy** [comment]
Can you send a screenshot of the contents of the actual folder in your system? (Settings > Locations > Browse profile folder)

**Comment by Existingperson26** [comment]
![image](https://github.com/ControlCompany/ControlCompany/assets/156600711/465f6187-3fa9-4768-8acb-3cf4990a355a)
![image](https://github.com/ControlCompany/ControlCompany/assets/156600711/ac7b54bd-57d0-4e9c-8561-eb3406025e41)
![image](https://github.com/ControlCompany/ControlCompany/assets/156600711/2b37ea7a-04fe-49b1-82d4-b27804755dc5)
Not exactly sure what one helps but i got what i could

**Comment by JustCallMeQuincy** [comment]
Have you launched the game at least once, for the configs to generate?

**Comment by Existingperson26** [comment]
Yes i have, quite a few times in fact

**Comment by JustCallMeQuincy** [comment]
Can you check if there's a config for ControlCompany in the `BepInEx\config\` folder?

**Comment by Existingperson26** [comment]
![image](https://github.com/ControlCompany/ControlCompany/assets/156600711/7fb6b0f4-1af0-4c6d-a30f-13449fb5c4a9)
its not there, i've tried uninstalling and reinstalling the mod and starting the game over and over. It just doesn't recognize the mod being there

**Comment by Existingperson26** [comment]
I got it working. Not sure exactly how but i am not gonna poke around much more

**Comment by JustCallMeQuincy** [comment]
Sounds good. This issue can be closed
