### ISSUE TITLE
Switching Targets

### ISSUE THREAD

**Issue by Ruvexai** [ControlCompany/ControlCompany#59]
When someone dies, they do not register as a target, this is bad for long-term games when your trying to troll ur friends but gets rlly annoying quickly

**Comment by Ruvexai** [comment]
and when i mean they dont register they dont register even if there alive after dying

**Comment by JustCallMeQuincy** [comment]
I will test this soon and add more info here once I have it

**Comment by JustCallMeQuincy** [comment]
I was unable to reproduce this bug.
Can you update to the latest version and try to reproduce this?

If you can, please (if possible) provide a video of the bug happening.

Closing this issue, assuming it's been resolved in one of the latest updates, feel free to re-open if you can reproduce it.
