### ISSUE TITLE
Question: What are your plans for this mod?

### ISSUE THREAD

**Issue by Sh0otgun** [ControlCompany/ControlCompany#6]
It this mod going to be a goofy mod you have to troll your friends?
Or is it going to become something you could consider being a completely new way to play the game with(or against) friends?

Also you should make a discord, or a official thread on the LC Modding discord.

**Comment by klampzlamps** [comment]
I have a thread in the LC modding discord here: https://discord.com/channels/1169792572382773318/1194847389924732988

As for your question, yes I’ll be turning it into something more. Akin to a new game mode for the whole lobby. Right now the mod is to just let people have fun but more will is definitely planned.

**Comment by Sh0otgun** [comment]
Thanks for the quick response!
The link to the thread you sent isn't working for me for some reason.
Are we in the same LC Modding discord? This is the one I'm in: https://discord.gg/lcmod

**Comment by klampzlamps** [comment]
Ah that’s a different discord than the one above, but I just posted to that one as well! Thanks!
