### ISSUE TITLE
Nobody is able to join me

### ISSUE THREAD

**Issue by sivlare** [ControlCompany/ControlCompany#62]
I have a public server made, and Ive tried relaunching and waiting for a while but nobody is still joining. My friends also cant join and I am unsure what to do. The only three mods i have installed right now are BepInExPack, LC_API, and controlcompany. please help.

**Comment by sivlare** [comment]
the page said Im the only one who needs to have it and host the server but its not letting anyone join ?? ?

**Comment by JustCallMeQuincy** [comment]
Try disabling/uninstalling LC_API and see if others can join then

**Comment by Ruvexai** [comment]
sometimes LC_API is unneeded and can cause people to have the error message when they join

**Comment by sivlare** [comment]
yeah it was LC_API thank you
