### ISSUE TITLE
Eyeless dog and Ghost Girl not working correctly in last version.

### ISSUE THREAD

**Issue by Nightmare4ever** [ControlCompany/ControlCompany#64]
When you press RMB so the eyeless dog to charge towards where you're looking, it does the charging animation but does not charge nor kill.
The Ghost Girl appears invisible and I can't make it appear, tried pressing LMB & RMB and nothing happened.

**Comment by klampzlamps** [comment]
These two monsters are in experimental mode, meaning they aren’t fully implemented yet. Closing in favour of #37
