### ISSUE TITLE
Mod Won't Launch

### ISSUE THREAD

**Issue by CodyDaKlutz** [ControlCompany/ControlCompany#69]
While trying to launch the game via thunderstore the terminal says "[Warning:   BepInEx] Plugin [ControlCompany 1.0.6] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update". To my knowledge that version of BepInEx doesn't exist.

**Comment by klampzlamps** [comment]
It’s just a warning, the mod should still work. Let me know if it doesn’t though

**Comment by CodyDaKlutz** [comment]
youre right. i feel dumb XD, i didnt load into a planet and was wondering why i couldnt do it XDXD
