### ISSUE TITLE
Unable to move when spawning in monster, then sudden crash to menu

### ISSUE THREAD

**Issue by Shark-with-a-Drill** [ControlCompany/ControlCompany#71]
So far happened on Dine, Titan, and March.

What happens is i am spectating and press F1 and i load in, but I cannot move or look around. Sometimes after a few seconds, I can move again such as activating the jester, then moving. However sometimes I cannot move at all and just crash to menu.

Other times, I am not able to spawn the monster at all, and just get stuck spectating a random part of the map the person I'm spectating walked past (such as stuck spectating an open door), or other times "spectating" the bottom of the map below everything even if the person is still alive/in the building.

Whatever the case, the most common thread seems to be not following the person I'm spectating, and when I go ghost mode, I am not able to freely move around, and when I spawn in the monster after, I am stationery and after a minute or so, the game crashes to menu.

Possible interacting mods are More Company and Late Company, however they were working fine just a few hours ago and now do not work. I installed DanceTools console to try other interactions but they don't seem to do anything.

**Comment by JustCallMeQuincy** [comment]
Would you mind perhaps trying to recreate the bug without other mods installed?

**Comment by JustCallMeQuincy** [comment]
Closing this issue, assuming it's been resolved.
