### ISSUE TITLE
[MOD BALANCING] Give monsters' handicaps to players too

### ISSUE THREAD

**Issue by NotSoSeriouss** [ControlCompany/ControlCompany#72]
Players playing as the monsters should have or should be prompted(keybind) to have the monsters handicaps:
Eyeless dogs: Can't see
Forest Giants: Can't hear
Bracken: Can't kill if being watched unless the looktime is over 2 seconds
Jester: Can't move if winding and winding time is accurate
Coilheads: Move only if not being watched
Ghost Girl: Can pick a single player and teleport behind him every 45 seconds becoming visible for 15 and then back invisible. If looked at 3 times in these events then she can enter rage mode and follow and attack said player.
And more...

Talking about the actual implementation: It could be a nice idea to use the already implemented event handler. I don't know if the enemies that you get to control in game are actually the entities with just a movement controller rehaul, but, in that case the game's monster events would still be active in the background and it should be trivial to intercept and use them.

**Comment by klampzlamps** [comment]
Related to #74 , this is something in the works already
