### ISSUE TITLE
Baboon hawk can't attack or pick up items.

### ISSUE THREAD

**Issue by Autumnis** [ControlCompany/ControlCompany#75]
Should be self explanatory. If getting near a player, the baboon hawk can't attack them, and there's no control to pick up items.

**Comment by SSpec77** [comment]
I don’t think the picking up animation was fully implemented yet. Hoarding bugs pickup controls is RMB to drop and pickup, yet the Baboon Hawk has no skill ( no first or secondary ) also Baboon Hawks hunt in packs, If there is one Crew Member and You as the Baboon Hawk, It shouldn’t let you attack. If there is One crew and 2 Baboon Hawks, then you might be able to attack. Also Baboon Hawks only pick up Flashy and Colorful Items. If the Fight ( Crew VS Baboon Hawk ) Is an even fight, they wont take there chances, hope this helps

**Comment by Autumnis** [comment]
> I don’t think the picking up animation was fully implemented yet. Hoarding bugs pickup controls is RMB to drop and pickup, yet the Baboon Hawk has no skill ( no first or secondary ) also Baboon Hawks hunt in packs, If there is one Crew Member and You as the Baboon Hawk, It shouldn’t let you attack. If there is One crew and 2 Baboon Hawks, then you might be able to attack. Also Baboon Hawks only pick up Flashy and Colorful Items. If the Fight ( Crew VS Baboon Hawk ) Is an even fight, they wont take there chances, hope this helps

In game, singular baboon hawks can very much attack players, and they're capable of picking up any item.

**Comment by JustCallMeQuincy** [comment]
I tested this and was able to kill players.
Picking up items is indeed not implemented yet

**Comment by klampzlamps** [comment]
Picking up items is now implemented with the release of v1.0.8, closing issue
