### ISSUE TITLE
all players are immortal

### ISSUE THREAD

**Issue by gamerkid666** [ControlCompany/ControlCompany#76]
with this mod installed all players are immortal for some reason. we cant take fall damage, kill with weapons, die to monsters, nothing.

**Comment by RunnyMoney** [comment]
LC_API 3.4.1 fixed it

**Comment by gamerkid666** [comment]
> LC_API 3.4.1 fixed it

yep just saw that! ofc that happens right when i say something lol

**Comment by klampzlamps** [comment]
closing issue as it's unrelated to the mod and an update to another mod fixes it
