### ISSUE TITLE
constant popup

### ISSUE THREAD

**Issue by ietesla** [ControlCompany/ControlCompany#77]
getting a popup that's like "Scan objects on the ship!" constantly. It seems to be linked to this mod.

**Comment by klampzlamps** [comment]
Hi, any steps to reproduce this issue? Do you have any other mods installed?

**Comment by ietesla** [comment]
I have biggerlobby installed, mimic doors, shiplobby, skinwalker mod, spectateenemies, helmet cameras.
Do any of those mods seem like they'd have incompatabilities?

**Comment by klampzlamps** [comment]
Nothing in ControlCompany should have a popup on your screen that says "Scan objects on the ship!" so my assumption is that it could be another mod that's causing the issue.

**Comment by JustCallMeQuincy** [comment]
Would you mind trying to recreate this issue without any other mods installed?

**Comment by ietesla** [comment]
Recreating the issue right now, slowly disabling each mod i have

**Comment by ietesla** [comment]
HelmetCameras, Skinwalkers, Mimics, and LethalPresents don't seem to be the cause.

The mods i have remaining are InputUtils, ShipLobby, MoreItems, LC_API, BiggerLobby, and of course BepinEX

**Comment by ietesla** [comment]
After disabling everything except for BiggerLobby and LC_API (and bepin), it's still happening.
Will see if disabling those two fixes it

**Comment by ietesla** [comment]
Surely enough, biggerlobby and LC_API seem to be the incompat here. No constant popups now

**Comment by ietesla** [comment]
This was caused by LC_API. it's fixed with an update now. Wasn't due to this mod!

**Comment by klampzlamps** [comment]
Glad it’s been fixed :)

**Comment by JustCallMeQuincy** [comment]
Thanks for testing!
