### ISSUE TITLE
[Suggestion] No attacking on monster mod

### ISSUE THREAD

**Issue by SameSpecters** [ControlCompany/ControlCompany#78]
Hey !
I see when we are on monster mode, some monsters have their attack automatic. For exemple, the Hoarding Bug be angry on some reasons et he attack himself if we are close to a player, or if we control the Forest Keeper, just be near a player to eat them. I think it's so sad whe can't have the control on that attack actions.

It can be possible to make that manually ? Like a new keybind for "Attack mode" and "Standby mode" for the Hoarding bug, or an "Attack bind" for some monsters? It can be fun see player Negociate their own life against a monster (who he is controlled by player, and no harming), for exemple !

**Comment by JustCallMeQuincy** [comment]
Something like this is in the works :D

**Comment by ZachFNF** [comment]
Please add this it’s an amazing suggestion

**Comment by nogsmcgogs** [comment]
Seconding this! Came here to request it. Usually I just wanna freak my friends out, not kill them straight away lol

**Comment by klampzlamps** [comment]
Looked into this and unfortunately the hit box to attack players is done on the client side (I.e their side) which means it’s not possible for the host to control this behaviour

**Comment by nogsmcgogs** [comment]
Aw man, that's disappointing :( thank you for looking into it though!
