### ISSUE TITLE
Small configuration request

### ISSUE THREAD

**Issue by Hna1243** [ControlCompany/ControlCompany#79]
Edit: New to making an account on github. So i dont know how to delete a post. Closing this in favor of #2 

Not sure if this has already been made, but i'll make it anyway.

Me and a friend want to be able to controlcompany together. We have a large group of friends (we aren't exactly lethal company experts) and are kinda gullible to what is being told to them. So playing as two bracken best friends can be brushed off as "a bug".

Because of this, I'd like a configuration option be made in the config file. That (when enabled) allows 2 players to play as a monster at the same time. Even without being the host.
The host needs to make this config enabled. So it likely won't cause any issues besides accidents.

Unless the mod's actually unstable with two players playing at once. I guess then this can't be immediately added.

**Comment by JustCallMeQuincy** [comment]
Closing this since it's a duplicate
