### ISSUE TITLE
[Bug report] Controlled characters can walk through the main entrance (prop) doors into the void, on Mansion maps

### ISSUE THREAD

**Issue by JustCallMeQuincy** [ControlCompany/ControlCompany#8]
# Describe the bug
When inside of a Mansion map, any controllable character that is *not* the regular player (Ghost mode, Snare flea, Bunker Spider, etc..) can walk through the prop main entrance door to fall into the void.

# What is supposed to happen?
The doors should be solid.

# What actually happens?
The doors don't have clipping on them.

# Illustration of the issue
https://youtu.be/IE6CoD28Cl4

**Comment by JustCallMeQuincy** [comment]
After further testing, this is also the case on the Facility layout maps

**Comment by JustCallMeQuincy** [comment]
I found that - as of V1.0.3 - Hoarding bugs can drop loot right outside of the noclip door, making it impossible for players (or even the lootbug itself) to grab it

**Comment by klampzlamps** [comment]
Yep, that's a consequence of being able to walk through all other doors as the monster/ghost. There could be a fix where for just the main entrance door there will be a collider. I'll mark it down for a future update.

**Comment by DarkFlyper** [comment]
Honestly make it so that the monster can take the door and go outside for maximum trolling

**Comment by klampzlamps** [comment]
Resolved since v1.1.1
