### ISSUE TITLE
Entity is not where it is supposed to be

### ISSUE THREAD

**Issue by ZachFNF** [ControlCompany/ControlCompany#82]
**Describe the bug**
Sometimes the entity just dosent move with where you control and employees cant see you unless you rebecome the entity.

**To Reproduce**
Play for a while as entitys and notice some employees cant see you

**Expected behavior**
You would be able to move it anywhere without it getting stuck or not moving

**Screenshots**
I dont have any right now but will add some later

**Mod version (please complete the following information):**
1.0.7

**Additional context**
On your screen the entity is in front of you while you are controlling it but employees just dont see you because where you actually are is where you are stuck, also if you switch to AI control you can see where you actually are because it teleports you to the position you are visible in.

**Comment by ZachFNF** [comment]
I found out this was due to locked doors, so instead, please make locked doors collidable

**Comment by ZachFNF** [comment]
If you walk through a locked door no one can see you because your stuck at the locked door

**Comment by JustCallMeQuincy** [comment]
That sounds pretty logical, thanks for testing! :D

**Comment by klampzlamps** [comment]
this is an interesting issue, will look into it

**Comment by klampzlamps** [comment]
Fixed the issue with the lock door sync by not letting monsters walk through locked doors, instead the doors will open if they touch it. Should resolve the desync issue.
