### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by MaidChanNaru** [ControlCompany/ControlCompany#83]
**Describe the bug**
I downloaded the Mod form ThunderStore Webside and the ControlCompany.ControlCompany.cfg file was missing.

**To Reproduce**
Download the mod from ThunderStore

**Expected behavior**
All files already in the mod

**Screenshots**

**Mod version (please complete the following information):**
1.0.7

**Additional context**
I tried everything but couldnt find the file. Please help
![image](https://github.com/ControlCompany/ControlCompany/assets/137607506/05245272-09fa-42d0-94db-365502fa112d)

**Comment by JustCallMeQuincy** [comment]
Hi! The config file generates as soon as you pull the lever to land on a moon. A fix for this is being investigated

**Comment by klampzlamps** [comment]
with the release of v1.0.8, the config file generates when the game first opens.
