### ISSUE TITLE
Hoarding Bug can't attack.

### ISSUE THREAD

**Issue by Autumnis** [ControlCompany/ControlCompany#84]
When running into players as the hoarding bug while angry, you simply collide with them and do not deal any damage to them. If you switch to AI control it works fine.

1.0.7

**Comment by Nzii3** [comment]
I don't think that's implemented yet, probably will be implemented soon in a future release.

**Comment by klampzlamps** [comment]
this is now possible as of v1.0.8, the bug will deal damage to a player while in angry mode
