### ISSUE TITLE
To stop controlling chat.

### ISSUE THREAD

**Issue by weirdguy9** [ControlCompany/ControlCompany#86]
I was playing with the mod for a little while and it started making me say weird stuff, the blue text that everyone can see goes off.

                                                                        I just find it annoying.

**Comment by klampzlamps** [comment]
What blue text? The mod doesn’t control the chat at all. Do you have other mods installed?

**Comment by weirdguy9** [comment]
> What blue text? The mod doesn’t control the chat at all. Do you have other mods installed?

well if i played it for a little while then it would make me say weird stuff even though i did not type it. and it would even say in the blue text i love the control company mod and then put my username right after so people know im using it.

**Comment by JustCallMeQuincy** [comment]
What other mods do you have installed?

**Comment by weirdguy9** [comment]
chat commands, game master

**Comment by weirdguy9** [comment]
> What blue text? The mod doesn’t control the chat at all. Do you have other mods installed?

you know how when somebody starts the ship it would say that in chat with blue text, Thats what it does

**Comment by klampzlamps** [comment]
What.. um where did you install the mod from?

**Comment by JustCallMeQuincy** [comment]
And do you perhaps have a screenshot?

**Comment by weirdguy9** [comment]
i dont have a screen shot and it was from r2modman

**Comment by klampzlamps** [comment]
that is interesting.. there is nothing in the mod that is remotely close to do anything like that so there are two cases I can think of:

1. The mod you downloaded has been re-uploaded with injected code
2. The other mods you have is detecting ControlCompany and forcing you to type that

If it still continues, uninstall the mod and re-install it directly from Thunderstore

**Comment by weirdguy9** [comment]
> that is interesting.. there is nothing in the mod that is remotely close to do anything like that so there are two cases I can think of:
> 
> 1. The mod you downloaded has been re-uploaded with injected code
> 2. The other mods you have is detecting ControlCompany and forcing you to type that
> 
> If it still continues, uninstall the mod and re-install it directly from Thunderstore

I'll try to get a screen shot with the mods i have currently and send it here it might take a while so you could come back tomorrow.

**Comment by weirdguy9** [comment]
the things i have seen it say NOT TO BE WEIRD is "i hate n**"   "Injecting malware 95% done"   "Im gay"  "i love using thunderstore mods"          "i love mods UWU"    thats basically it and my friends say what the heck and im like what

**Comment by klampzlamps** [comment]
That is **definitely not** something we have in the legitimate mod

**Comment by weirdguy9** [comment]
and it is truly threatening to me

**Comment by klampzlamps** [comment]
Try running the game with all the mods disabled except ControlCompany as well

**Comment by klampzlamps** [comment]
I saw that you marked this as closed, were you able to figure out what the issue was?

**Comment by weirdguy9** [comment]
uhh so i got a pic
![Screenshot 2024-01-16 164014](https://github.com/ControlCompany/ControlCompany/assets/97771215/290eefea-bf87-462a-afb3-da058b80dadb)

**Comment by weirdguy9** [comment]
gross

**Comment by weirdguy9** [comment]
i was talking to my friends and it put THAT in chat

**Comment by klampzlamps** [comment]
I would just uninstall every mod you have and reinstall it from the official thunderstore page, it’s most likely one of the other mods interfering

**Comment by weirdguy9** [comment]
ok i did thanks a bunch for help
