### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Saberlily1215** [ControlCompany/ControlCompany#88]
I downloaded it correctly and it was working one moment, but when I restarted my game it didn't work anymore.

**Comment by klampzlamps** [comment]
Can you describe the issue more? Are you the host and did you pull the lever?

**Comment by Bendymachine0707** [comment]
mine isn't working for some reason

**Comment by JustCallMeQuincy** [comment]
@Bendymachine0707 can you provide more information?

**Comment by Bendymachine0707** [comment]
> @Bendymachine0707 can you provide more information?

Yeah it like worked first day doesn’t work any more and I made a new thunderstorm account still doesn’t work it doesn’t pop up on the corner

**Comment by Bendymachine0707** [comment]
Ima try when I get to my house

**Comment by Bendymachine0707** [comment]
Thank you> While only having ControlCompany installed, launch the game (`Start modded`) and host a session
> 
> Then pull the lever
> 
>

**Comment by JustCallMeQuincy** [comment]
Closing this assuming all issues have been resolved. Feel free to re-open if that's not the case

**Comment by JustCallMeQuincy** [comment]
Did you change anything between restarts? (Like adding different mods)
