### ISSUE TITLE
the mod is not working, it shows when i land in the moon on the top right screen corner but when i try to get into the ghost mode it does not let me.

### ISSUE THREAD

**Issue by Cosmp** [ControlCompany/ControlCompany#91]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Mod version (please complete the following information):**
You can find the version of the mod in the Thunderstore mod manager.

**Additional context**

**Comment by Cosmp** [comment]
i tried rebinding it already it did not work.
sry about the form thing im kinda new

**Comment by JustCallMeQuincy** [comment]
Which key did you rebind it to?
Did you install the mod from the Thunderstore or R2modman?
Do you have any other mods installed?

**Comment by Cosmp** [comment]
to the "i" button
i installed it from thunderstore tried two versions 1.0.7 and 1.0.6
yes, tried with and without same problem.

**Comment by JustCallMeQuincy** [comment]
# Assuming that you're using the r2modmanager or the Thunderstore, please try the following:


## 1. In your profile, go to `Settings` → `Profile` → `Change profile`
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/f9f3cec1-1a82-469d-b579-285f1c6c8da6)

## 2. Click on `Create new`, name the profile (anything) and click on `Create`
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/a1714854-d439-4df4-a735-875f3c7e243a)
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/51d901aa-84d8-4e18-8e6f-3f0d329f270b)

## 3. Click on `Select profile` with the new profile selected
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/94aa5887-6d82-4e23-81e7-2da5731edb1d)

## 4. Go to the `Online` tab and install `ControlCompany`
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/27df1bbc-c963-436c-a79f-e0c0ea46c35a)
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/483b3e2c-60dc-4fe6-8f3d-d83957b23d23)

## 5. After installing, click on `Start modded`
![image](https://github.com/ControlCompany/ControlCompany/assets/71931404/b0473fcc-5662-4312-a856-9ee0e1947129)

**Comment by JustCallMeQuincy** [comment]
Closing this issue, assuming it's been resolved.
