### ISSUE TITLE
The mod does not work

### ISSUE THREAD

**Issue by Cosmp** [ControlCompany/ControlCompany#92]
i added the mod correctly and it shows in the game however when i press F1 to get into the ghost mode it does not let me.
when i press U to hide the UI it hides it and i receive a weird error in the bepinx terminal, however i tried another mods and they work perfectly.
![Screenshot 2024-01-16 124627](https://github.com/ControlCompany/ControlCompany/assets/156788975/b1ef7030-36c6-4a81-89a4-48833da3b0b2)

**Comment by JustCallMeQuincy** [comment]
I was unable to recreate this. Do you have any other mods installed?

**Comment by Cosmp** [comment]
yes i tried with them installed it did not work, so i removed them it also gave the same error

**Comment by JustCallMeQuincy** [comment]
Once you've done this, please try recreating the issue

**Comment by JustCallMeQuincy** [comment]
Closing this issue, assuming it's been resolved.
