### ISSUE TITLE
Can't spawn masked on titan

### ISSUE THREAD

**Issue by redphoenix23554** [ControlCompany/ControlCompany#93]
So, something called lasso (wtf is that thing?) is taking up one of the function keys, and as such, I can no longer control the masked. So is there a way to configure which monsters show up or has it been removed from titan?

Also, why is the masked not available as an outdoor entity on rend/dine? It can naturally be both in and outside so...

**Comment by klampzlamps** [comment]
Will be added once masked enemy has been moved to the stable list

**Comment by klampzlamps** [comment]
masked will be the focus of next patch (v1.0.9)

**Comment by klampzlamps** [comment]
closing in favour of #37
