### ISSUE TITLE
when i get into a hosted game it doesnt show the ui and none of the buttons work, bepinex has no red text either

### ISSUE THREAD

**Issue by TheCompany12** [ControlCompany/ControlCompany#96]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Mod version (please complete the following information):**
You can find the version of the mod in the Thunderstore mod manager.

**Additional context**

**Comment by ZachFNF** [comment]
press u

**Comment by Autumnis** [comment]
you have to land first
