### ISSUE TITLE
Audio not working in game 

### ISSUE THREAD

**Issue by nomCarver97** [ControlCompany/ControlCompany#97]
**Describe the bug**
When i boot the game, audio works in menu. When I host my own game, it takes a couple restarts to get audio working. When audio finally works, audio cuts off anytime a player joins. I tried vanilla and had no issues.

Additionally, I get this message using BepInEx Pack : "[Warning:   BepInEx] Plugin [ControlCompany 1.0.7] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update" However, the BepInEx Pack version I have installed is v5.4.2100, the latest version.

**Mod version:
v1.0.7

**Comment by klampzlamps** [comment]
This doesn’t seem like it’s related to the mod, the mod doesn’t modify the audio in anyway.

**Comment by JustCallMeQuincy** [comment]
Closing this for now.
