### ISSUE TITLE
Mod targets version of BepInEX that does not exist

### ISSUE THREAD

**Issue by HoboSamurai** [ControlCompany/ControlCompany#99]
**Describe the bug**
When launched with only it and latest bepin, BepIn console shows yellow error saying "[Warning:   BepInEx] Plugin [ControlCompany 1.0.7] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update" Mod does not load into game.

**To Reproduce**
Downloaded mod, launched game.

**Expected behavior**
mod to load in by itself, maybe another mod caused problems. loaded by itself still did not load in,

**Screenshots**
![Screenshot 2024-01-16 190605](https://github.com/ControlCompany/ControlCompany/assets/156861373/de72ffeb-f270-46f8-a7fa-d529fb177edf)

![Screenshot 2024-01-16 190732](https://github.com/ControlCompany/ControlCompany/assets/156861373/ae03e788-68c7-40aa-ad99-b51ac613c32d)

**Mod version (please complete the following information):**
Attempted all mod versions, same errors. last attempted 1.0,7
game version V49

**Comment by nomCarver97** [comment]
I have the same issue. I get no audio in game.

**Comment by klampzlamps** [comment]
That message is just a warning, the mod still works. Have you tried hosting a game and landing on a moon?

**Comment by HoboSamurai** [comment]
> That message is just a warning, the mod still works. Have you tried hosting a game and landing on a moon?

No, Im dumb apparently lmao. thank you so much. I thought it would have loaded a config or on launch like a goober!
